services:
  - type: web
    name: mern-registration-app
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/registration_app
      - key: PORT
        value: 10000
      - key: EXCEL_FILE_PATH
        value: ./data/registrations.xlsx
      - key: NODE_ENV
        value: production 